services:
  Ustal\StreamHub\Component\Storage\StreamBackendInterface:
    alias: '%stream_hub.backend_service%'

  stream_hub.context.inner:
    alias: '%stream_hub.context_service%'

  Ustal\StreamHub\Component\Context\StreamContextInterface:
    alias: Ustal\StreamHub\SymfonyBundle\Context\ViewAwareStreamContext

  Ustal\StreamHub\Component\Service\PluginDefinitionRegistry:
    factory: ['@Ustal\StreamHub\SymfonyBundle\Factory\StreamHubRuntimeFactory', buildPluginRegistry]
    arguments:
      $builder: '@Ustal\StreamHub\Component\Service\PluginDefinitionBuilder'
      $enabledPlugins: '%stream_hub.enabled_plugins%'
      $rootSlots: '%stream_hub.root_slots%'

  Ustal\StreamHub\Component\Service\SlotTree:
    factory: ['@Ustal\StreamHub\SymfonyBundle\Factory\StreamHubRuntimeFactory', buildSlotTree]
    arguments:
      $registry: '@Ustal\StreamHub\Component\Service\PluginDefinitionRegistry'
      $rootSlots: '%stream_hub.root_slots%'

  Ustal\StreamHub\Component\Service\PluginManager:
    factory: ['@Ustal\StreamHub\SymfonyBundle\Factory\StreamHubRuntimeFactory', buildPluginManager]
    arguments:
      $registry: '@Ustal\StreamHub\Component\Service\PluginDefinitionRegistry'

  Ustal\StreamHub\Core\Command\CommandBusInterface:
    factory: ['@Ustal\StreamHub\SymfonyBundle\Factory\StreamHubRuntimeFactory', buildCommandBus]
    arguments:
      $factory: '@Ustal\StreamHub\Core\Command\CommandBusFactory'
      $registry: '@Ustal\StreamHub\Component\Service\PluginDefinitionRegistry'
      $handlers: !tagged_iterator stream_hub.command_handler

  Ustal\StreamHub\Core\Render\SlotRendererInterface:
    alias: Ustal\StreamHub\Core\Render\SlotRenderer

  Ustal\StreamHub\Core\Render\StreamPageRendererInterface:
    alias: Ustal\StreamHub\Core\Render\StreamPageRenderer

  Ustal\StreamHub\Core\Plugins\CoreStream\Command\CreateStreamCommandHandler:
    tags: ['stream_hub.command_handler']

  Ustal\StreamHub\Core\Plugins\CoreStream\Command\JoinStreamCommandHandler:
    tags: ['stream_hub.command_handler']

  Ustal\StreamHub\Core\Plugins\CoreStream\Command\AppendStreamEventCommandHandler:
    tags: ['stream_hub.command_handler']

  Ustal\StreamHub\Core\Plugins\CoreStream\Command\MarkStreamReadCommandHandler:
    tags: ['stream_hub.command_handler']
