services:
  _defaults:
    autowire: true
    autoconfigure: true

  Ustal\StreamHub\SymfonyBundle\:
    resource: '../../'
    exclude:
      - '../../Command/'
      - '../../Context/'
      - '../../DependencyInjection/'
      - '../../Factory/'
      - '../../Render/'
      - '../../Resources/'
      - '../../Tests/'

  Ustal\StreamHub\SymfonyBundle\StreamHubBundle:
    public: true

  stream_hub.identifier_generator.random_hex:
    class: Ustal\StreamHub\Component\Identifier\Generator\RandomHexIdentifierGenerator

  stream_hub.identifier_generator.uuid_v4:
    class: Ustal\StreamHub\Component\Identifier\Generator\UuidV4IdentifierGenerator

  stream_hub.identifier_generator.uuid_v7:
    class: Ustal\StreamHub\Component\Identifier\Generator\UuidV7IdentifierGenerator

  stream_hub.command_bus.inner:
    class: Ustal\StreamHub\Core\Command\CommandBus
    arguments:
      $handlers: !tagged_iterator stream_hub.command_handler

  Ustal\StreamHub\Core\Command\CommandBusInterface:
    class: Ustal\StreamHub\Core\Command\GuardedCommandBus
    arguments:
      $inner: '@stream_hub.command_bus.inner'
      $guards: !tagged_iterator stream_hub.command_guard

  Ustal\StreamHub\Core\Command\ModelCommandBusInterface:
    alias: stream_hub.model_command_bus

  stream_hub.model_command_bus:
    class: Ustal\StreamHub\Core\Command\CommandBus
    arguments:
      $handlers: !tagged_iterator stream_hub.model_command_handler
